[package]
name = "uefi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
uefi-proto = { path = "../uefi-proto" }
uefi-common = { path = "../uefi-common" }
tonic.workspace = true
tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true
hyper-util = { version = "0.1", features = ["tokio"] }
tower = { version = "0.4", features = ["util"] }
http = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
uuid.workspace = true
tokio-stream = { version = "0.1", features = ["net"] }
