#!/usr/bin/env python3
"""gen_mmr_table.py — печь EpaConfig.h пробника из MMR-таблицы (цикл A).

Спека docs/superpowers/specs/2026-09-14-bif-driver-recon-design.md §4-5
(таблица MMR = JSON-контракт, пробник без runtime-фроззинга). Валидирует
схему (--check), сортирует по sequence, генерирует заголовок для
BifEpaProbe.c. Не часть движка; запуск вручную или из build_bif_epa.sh:

    hack/gen_mmr_table.py --mmr docs/reports/2026-09-14-uncore-bif-mmr.json \
        --mode write --reset warm --pause-ms 3000 \
        --out docker/edk2/UefiPatcherBifPkg/BifEpaProbe/EpaConfig.h
"""
import argparse
import json
import sys

SCHEMA_ERR = "schema error: "
HEX_FIELDS = ("and_mask", "or_value")


def parse_hex(v, what):
    if not isinstance(v, str) or not v.lower().startswith("0x"):
        sys.exit(SCHEMA_ERR + f"{what}: {v!r} must be a 0x-hex string")
    n = int(v, 16)
    if not 0 <= n <= 0xFFFFFFFF:
        sys.exit(SCHEMA_ERR + f"{what}: {v!r} out of u32")
    return n


def validate(doc):
    if not isinstance(doc, dict) or "entries" not in doc:
        sys.exit(SCHEMA_ERR + "top-level object with 'entries' required")
    if doc.get("reset") not in ("warm", "cold"):
        sys.exit(SCHEMA_ERR + "reset: 'warm'|'cold'")
    seqs = []
    for i, e in enumerate(doc["entries"]):
        w = f"entries[{i}]"
        for f in ("tag", "purpose", "access", "width", "and_mask", "or_value", "sequence"):
            if f not in e:
                sys.exit(SCHEMA_ERR + f"{w}: missing {f}")
        if e["width"] != 4:
            sys.exit(SCHEMA_ERR + f"{w}.width: only 4 supported")
        parse_hex(e["and_mask"], f"{w}.and_mask")
        parse_hex(e["or_value"], f"{w}.or_value")
        a = e["access"]
        if a.get("kind") == "mmio32":
            addr = a.get("addr")
            if not isinstance(addr, str) or not addr.lower().startswith("0x"):
                sys.exit(SCHEMA_ERR + f"{w}.access.addr: 0x-hex string required")
            int(addr, 16)
        elif a.get("kind") == "pci-cfg32":
            for f in ("bus", "dev", "fun", "off"):
                v = a.get(f)
                if not isinstance(v, int):
                    sys.exit(SCHEMA_ERR + f"{w}.access.{f}: int required")
            if not 0 <= a["off"] < 0x100:
                sys.exit(SCHEMA_ERR + f"{w}.access.off: CF8 path requires off<0x100")
        else:
            sys.exit(SCHEMA_ERR + f"{w}.access.kind: 'mmio32'|'pci-cfg32'")
        seqs.append(e["sequence"])
    if len(seqs) != len(set(seqs)):
        sys.exit(SCHEMA_ERR + "sequence values must be unique")


def entry_addr(e):
    a = e["access"]
    if a["kind"] == "mmio32":
        return int(a["addr"], 16)
    return (a["bus"] << 16) | (a["dev"] << 11) | (a["fun"] << 8) | a["off"]


def gen(doc, mode_write, cold, pause_ms):
    entries = sorted(doc["entries"], key=lambda e: e["sequence"])
    lines = [
        "// Generated by hack/gen_mmr_table.py from docs/reports/2026-09-14-uncore-bif-mmr.json",
        "// Spec: docs/superpowers/specs/2026-09-14-bif-driver-recon-design.md 5 (no runtime fuzzing)",
        "#ifndef EPA_CONFIG_H_",
        "#define EPA_CONFIG_H_",
        "",
        f"#define EPA_MODE_WRITE {1 if mode_write else 0}",
        f"#define EPA_RESET_COLD {1 if cold else 0}",
        f"#define EPA_PAUSE_MS {pause_ms}",
        f"#define EPA_ENTRY_COUNT {len(entries)}",
        "",
        "typedef struct {",
        "  CONST CHAR8  *Tag;",
        "  UINT8         Kind;  // 0 = MMIO32, 1 = PCI CF832",
        "  UINT64        Addr;",
        "  UINT32        AndMask;",
        "  UINT32        OrValue;",
        "} MMR_ENTRY;",
        "",
        f"STATIC CONST MMR_ENTRY  mMmrEntries[EPA_ENTRY_COUNT] = {{",
    ]
    for e in entries:
        kind = 0 if e["access"]["kind"] == "mmio32" else 1
        lines.append(f'  {{ "{e["tag"]}", {kind}, 0x{entry_addr(e):X}, '
                     f'0x{parse_hex(e["and_mask"], "and_mask"):08X}, 0x{parse_hex(e["or_value"], "or_value"):08X} }},')
    lines += ["};", "", "#endif", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mmr", required=True)
    ap.add_argument("--mode", choices=("read", "write"), default="read")
    ap.add_argument("--reset", choices=("warm", "cold"), default=None)
    ap.add_argument("--pause-ms", type=int, default=3000)
    ap.add_argument("--out", default=None)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    doc = json.load(open(args.mmr))
    validate(doc)
    if args.check:
        print(f"ok: {len(doc['entries'])} entries")
        return
    text = gen(doc, args.mode == "write", (args.reset or doc["reset"]) == "cold", args.pause_ms)
    if args.out:
        open(args.out, "w").write(text)
        print(f"wrote {args.out}: mode={args.mode} entries={len(doc['entries'])}")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
