apiVersion: v1
kind: Pod
metadata:
  name: uefipatcher-pod
  labels:
    app: uefipatcher
spec:
  containers:
    - name: engine
      image: uefipatcher-engine:latest
      env:
        - name: UEFIPATCHER_DATA
          value: /data
        - name: UEFIPATCHER_SOCK
          value: /run/uefipatcher/uefipatcher.sock
        - name: UEFIPATCHER_SESSION_TTL_SECS
          value: "864000"
        - name: UEFIPATCHER_SESSION_GC_INTERVAL_SECS
          value: "3600"
        - name: UEFIPATCHER_PURGE_ARTIFACTS
          value: "false"
      volumeMounts:
        - name: uefi-data
          mountPath: /data
        - name: uefi-sock
          mountPath: /run/uefipatcher
    - name: gateway 
      image: uefipatcher-gateway:latest
      env:
        - name: UEFIPATCHER_SOCK
          value: /run/uefipatcher/uefipatcher.sock
        - name: UEFIPATCHER_GATEWAY_LISTEN
          value: 0.0.0.0:8080
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: uefi-sock
          mountPath: /run/uefipatcher
    - name: webui
      image: uefipatcher-webui:latest
      ports:
        - containerPort: 3000
          #hostPort: 3000
  volumes:
    - name: uefi-data
      emptyDir: {}
    - name: uefi-sock
      emptyDir: {}
