// Generated by hack/gen_mmr_table.py from docs/reports/2026-09-14-uncore-bif-mmr.json
// Spec: docs/superpowers/specs/2026-09-14-bif-driver-recon-design.md 5 (no runtime fuzzing)
#ifndef EPA_CONFIG_H_
#define EPA_CONFIG_H_

#define EPA_MODE_WRITE 0
#define EPA_RESET_COLD 0
#define EPA_PAUSE_MS 3000
#define EPA_ENTRY_COUNT 1

typedef struct {
  CONST CHAR8  *Tag;
  UINT8         Kind;  // 0 = MMIO32, 1 = PCI CF832
  UINT64        Addr;
  UINT32        AndMask;
  UINT32        OrValue;
} MMR_ENTRY;

STATIC CONST MMR_ENTRY  mMmrEntries[EPA_ENTRY_COUNT] = {
  { "IOU0-Port2-bifurcation", 0, 0xE0010190, 0xFFFFFFF8, 0x00000008 },
};

#endif
